# Q1

We minimise the variance of portfolio, subject to constraints.

constraint 1: $\mu^T w = m$

constraint 2: $\mathbb{1}^Tw = 1$

In other words,
$$ \min_w {\frac{1}{2}w^T SRS w}  $$
s.t.
$$\mu^T w = m$$
$$\mathbb{1}^Tw = 1$$

To construct the Lagrangian,

$$\mathscr{L}(w, \lambda, \gamma) = {\frac{1}{2}w^T SRS w}  + \lambda (m -\mu^T w ) + \gamma (1-\mathbb{1}^Tw )$$

F.O.C.

w.r.t. $w$:

Let, $\frac{\partial L}{\partial w} = SRSw - \lambda \mu - \gamma \mathbb{1}=0$,

so we get $w^* = (SRS)^{-1}(\lambda \mu + \gamma \mathbb{1})$

w.r.t. $\lambda, \gamma$, we would simply get the constraints.


Three equations and three unknowns $w, \lambda, \gamma$,
- $  w= (SRS)^{-1}(\lambda \mu + \gamma \mathbb{1}) $
- $m = \mu^T w $
- $1 = \mathbb{1}^Tw$

The answer would be:
- $ \lambda = \frac{Am - B}{AC-B^2} $
- $ \gamma = \frac{C - Bm}{AC-B^2} $
- $  w= (SRS)^{-1}(\lambda \mu + \gamma \mathbb{1}) $

, where
- $A = \mathbb{1}^T (SRS)^{-1} \mathbb{1}$
- $B = \mu^T (SRS)^{-1} \mathbb{1} =  \mathbb{1}^T(SRS)^{-1}\mu $
- $C = \mu^T (SRS)^{-1} \mu$

In [1]:
import numpy as np

In [77]:
mu = np.array( [0.08, 0.1, 0.1, 0.14] )
sigma = np.array([0.12, 0.12, 0.15, 0.2])
S = np.diag(sigma)
One = np.ones(4)
m=0.1

def cal_ABC(R):
    A = One.T.dot(   np.linalg.inv( S.dot(R).dot(S) )   ).dot(One)
    B = mu.T.dot(   np.linalg.inv( S.dot(R).dot(S) )   ).dot(One)
    C = mu.T.dot(   np.linalg.inv( S.dot(R).dot(S) )   ).dot(mu)
    return A, B, C

def cal_lambda_gamma(A,B,C):
    lam = (A*m - B)/(A*C - B**2)
    gam = (C - B*m)/(A*C - B**2)
    return lam, gam

def cal_wstar(R):
    if np.linalg.det( S.dot(rho).dot(S) ) == 0: # the singular matrix has determiant = 0
        Zero = np.zeros(4)
        Zero[np.lexsort((mu*(-1), sigma))[0]] = 1
        # return the portfolio with only one assets that have lowest sigma and highest return
        return Zero
    A,B,C = cal_ABC(R)
    lam, gam = cal_lambda_gamma(A,B,C)
    w_star = np.linalg.inv( S.dot(R).dot(S) ).dot(  lam*mu + gam * One  )
    return w_star

In [78]:
# 1.1
rho = np.array([[1, 0.2, 0.5, 0.3],[0.2, 1, 0.7, 0.4],[0.5, 0.7, 1, 0.9],[0.3, 0.4, 0.9, 1]])
cal_wstar(rho)

array([ 0.76228686,  0.84419926, -0.98762956,  0.38114343])

In [79]:
# 1.2
rho = np.diag(One)
cal_wstar(rho)

array([0.29827662, 0.33694211, 0.21564295, 0.14913831])

In [82]:
# 1.3 
'''
In this case, we find that the correlation matrix is all one, 
which means those assets are all perfectly correlated. 
In another words, if asset A increase by 10%, asset B,C, and D will increase also 10%.
Thus, we pick only the asset with lowest var (because that is a minimisation prob) 
, and then highest return

def cal_wstar(R):
    if np.linalg.det( S.dot(rho).dot(S) ) == 0:  # the singular matrix has determiant = 0
        Zero = np.zeros(4)
        Zero[np.lexsort((mu*(-1), sigma))[0]] = 1 
        # return the portfolio with only one assets that have lowest sigma and highest return
        return Zero
    A,B,C = cal_ABC(R)
    lam, gam = cal_lambda_gamma(A,B,C)
    w_star = np.linalg.inv( S.dot(R).dot(S) ).dot(  lam*mu + gam * One  )
    return w_star
'''


rho = np.ones([4,4])
cal_wstar(rho)

array([0., 1., 0., 0.])

In [118]:
# 1.3 Interestedly, if I substract a tiny random from the all-one rho, to make it invertible
# the result is as the following.
rho = np.ones([4,4])
for i in range(4):
    for j in range(4):
        rho[i,j] += np.random.randn()/1_000_000
        
print(cal_wstar(rho))
print('Any tiny diff would be exaggerated, so that method does not work!')

[-5.4358827   7.58335372  8.61634298 -7.75070753]
Any tiny diff would be exaggerated, so that method does not work!


# 3

