# A Copy Paste Sheet

## 0. Tips of Pandas DataFrame
##  1. Class 对象
##  2. 遍历dir下文件
##  3. time魔术命令
##  4. 数据统计基本情况
##  5. 数据预处理
##  6. Get Data
##  7. 转换时间格式（待测试
##  8. Statistic Table Output
##  9. String in DataFrame
## 10. Date Features
## 11. Subplots
## 12. Get Dummy
## 13. Select and Shuffle (np array in and remove)
## 14. flip a dictionary

In [2]:
import numpy as np
import pandas as pd

# 0. Tips for Pandas DataFrame

In [ ]:
# return the loc of max/min
df.argmax()

In [ ]:
# return the # of unique value
df.nunique()

## 1. Class 对象

In [3]:
# 这是一个类
class debt():
    # 属性
    def __init__(self, n, rm, c, fv):
        self.n = n
        self.rm = rm
        self.c = c
        self.__fv = fv
        
    # 方法  
    def get_pv(self):
        return self.__fv
    
    def __pv_calc(self, n, rm, c, fv):
        pv =0
        interest = 0

        for i in range(n):
            interest = c* fv /((1+rm)**(i+1))
            pv += interest

        pv += fv/((1+rm)**n)

        return pv 
    
    def get_pv(self):
        return self.__pv_calc(self.n, self.rm, self.c, self.__fv)
    
# 这是一个对象
my_debt = debt(3, 0.05, 0.03, 100)

my_debt.get_pv()

94.55350394125902

# 2. 遍历 dir下文件

在我日常工作中，os用的最多的是在加载数据中，目标文件夹的遍历，在这里一同给到大家，方便你CV：

~~~python  
import pandas as pd
import os
import os.path

# 获取指定路径下的所有文件，文件夹
for parent, dirnames, filenames in os.walk(file_dir,  followlinks=True):
    for filename in filenames:
        dir_temp = os.path.join(parent, filename)
        df_temp = pd.read_csv(dir_temp, encoding='GB18030')

~~~

In [4]:
import pandas as pd
import os
import os.path

In [5]:
file_dir=os.getcwd()
file_dir

'/Users/mie/Desktop/CQF'

In [6]:
# 获取指定路径下的所有文件，文件夹
for parent, dirnames, filenames in os.walk(file_dir,  followlinks=True):
    for filename in filenames:
        dir_temp = os.path.join(parent, filename)   #把地址和文件名拼接
        print(dir_temp)
    print('-------------')

/Users/mie/Desktop/CQF/.DS_Store
/Users/mie/Desktop/CQF/CheatSheet.ipynb
-------------
/Users/mie/Desktop/CQF/教材 电子版/10. paul wilmott introduces quantitative finance.pdf
/Users/mie/Desktop/CQF/教材 电子版/7. frequently asked questions in quantitative finance 2nd edition.pdf
/Users/mie/Desktop/CQF/教材 电子版/3. 4. 5. Paul Wilmott on Quantitative Finance Vol 1-3, 2nd Ed.pdf
/Users/mie/Desktop/CQF/教材 电子版/6. （The_Wiley_Finance_Series）_Jon_Gregory－The_xVA_Challenge__Counterparty_Credit_Risk，_Funding，_Collateral，_and_Capital－Wiley_（2015）.pdf
/Users/mie/Desktop/CQF/教材 电子版/11. Machine Learning.pdf
/Users/mie/Desktop/CQF/教材 电子版/9. Derivatives_Models_on_Models.pdf
/Users/mie/Desktop/CQF/教材 电子版/8.Jackel- Monte-Carlo Methods In Finance.pdf
/Users/mie/Desktop/CQF/教材 电子版/2. Asset Price Dynamics, Volatility, and Prediction Stephen J. Taylor 2005.pdf
/Users/mie/Desktop/CQF/教材 电子版/1. Python_for_Finance__Mastering_Data－Driven_Finance_.pdf
-------------
/Users/mie/Desktop/CQF/Pre/.DS_Store
/Users/mie/Desktop/CQF/

In [38]:
# 获取指定路径下的所有文件，文件夹
for parent, dirnames, filenames in os.walk(file_dir,  followlinks=True):
    for filename in filenames:
        dir_temp = os.path.join(parent, filename)   #把地址和文件名拼接
        if dir_temp[-3:]=='xls':
            print(dir_temp)

/Users/mie/Desktop/CQF/Pre/Python前导课讲义/ex1.xls


### the other way

In [ ]:
import os

def print_file(path, level = 0):
    current_dir_file = os.listdir(path)
    for file in current_dir_file:
        file_path = os.path.join(path, file)
        print('\t'* level + file_path[file_path.rfind(os.sep)+1:])
        if os.path.isdir(file_path):
            print_file(file_path, level + 1)

# 3. time 魔术命令

In [9]:
%%time

2**1000

CPU times: user 8 µs, sys: 1 µs, total: 9 µs
Wall time: 11 µs


10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376

# 4. 数据统计基本情况

In [25]:
# 抓取出来csv文件有哪些
for parent, dirnames, filenames in os.walk(file_dir,  followlinks=True):
    for filename in filenames:
        dir_temp = os.path.join(parent, filename)   #把地址和文件名拼接
        if filename[-3:]=="csv":
            print(dir_temp)

/Users/mie/Desktop/CQF/Pre/CQF_Python_Primer/CQF_Python_Primer/AAPL.csv
/Users/mie/Desktop/CQF/Pre/Python前导课讲义/df2OV.csv
/Users/mie/Desktop/CQF/Pre/Python前导课讲义/faang_stocks.csv


In [26]:
%%time
data = pd.read_csv(r'/Users/mie/Desktop/CQF/Pre/Python前导课讲义/faang_stocks.csv')

print(data)
print(type(data))

            Date        AAPL         AMZN          FB         GOOG        NFLX
0     2009-12-31   26.061205   134.520004         NaN   308.832428    7.870000
1     2010-01-04   26.466835   133.899994         NaN   312.204773    7.640000
2     2010-01-05   26.512596   134.690002         NaN   310.829926    7.358572
3     2010-01-06   26.090879   132.250000         NaN   302.994293    7.617143
4     2010-01-07   26.042646   130.000000         NaN   295.940735    7.485714
...          ...         ...          ...         ...          ...         ...
2594  2020-04-23  274.287506  2399.449951  185.130005  1276.310059  426.700012
2595  2020-04-24  282.206085  2410.219971  190.070007  1279.310059  424.989990
2596  2020-04-27  282.405548  2376.000000  187.500000  1275.880005  421.380005
2597  2020-04-28  277.827911  2314.080078  182.910004  1233.670044  403.829987
2598  2020-04-29  286.953247  2372.709961  194.190002  1341.479980  411.890015

[2599 rows x 6 columns]
<class 'pandas.core.frame.D

In [27]:
print(data.index)

RangeIndex(start=0, stop=2599, step=1)


In [28]:
print(data.columns)

Index(['Date', 'AAPL', 'AMZN', 'FB', 'GOOG', 'NFLX'], dtype='object')


In [29]:
print(data.values)

[['2009-12-31' 26.06120491027832 134.52000427246094 nan 308.8324279785156
  7.869999885559082]
 ['2010-01-04' 26.466835021972656 133.89999389648438 nan
  312.20477294921875 7.639999866485596]
 ['2010-01-05' 26.512596130371094 134.69000244140625 nan
  310.8299255371094 7.358571529388428]
 ...
 ['2020-04-27' 282.4055480957031 2376.0 187.5 1275.8800048828125
  421.3800048828125]
 ['2020-04-28' 277.8279113769531 2314.080078125 182.91000366210935
  1233.6700439453125 403.8299865722656]
 ['2020-04-29' 286.9532470703125 2372.7099609375 194.19000244140625
  1341.47998046875 411.8900146484375]]


In [30]:
# 查看基本统计信息
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2599 entries, 0 to 2598
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    2599 non-null   object 
 1   AAPL    2599 non-null   float64
 2   AMZN    2599 non-null   float64
 3   FB      1999 non-null   float64
 4   GOOG    2599 non-null   float64
 5   NFLX    2599 non-null   float64
dtypes: float64(5), object(1)
memory usage: 122.0+ KB
None


In [31]:
print(data.describe())

              AAPL         AMZN           FB         GOOG         NFLX
count  2599.000000  2599.000000  1999.000000  2599.000000  2599.000000
mean    109.311866   717.898226   112.921926   665.300403   123.477451
std      65.143457   617.428749    58.198616   342.896046   121.875064
min      23.751026   108.610001    17.730000   217.220810     7.018571
25%      57.737783   232.279999    65.330002   322.277023    26.976428
50%      93.625145   387.600006   114.599998   572.553955    67.435715
75%     150.969185  1002.019989   168.834999   972.014984   185.250000
max     326.316681  2410.219971   223.229996  1526.689941   439.170013


# 5. 数据预处理 

用过excel的人，都会对excel中简化了的计算念念不忘，当然，python也提供了这一快捷方式。由于本节内容比较容易，我们在此只是把常用运算展示一下，不做深入讲解。
~~~python
df.sum(axis=1) # 每列/行求和结果
df.mean(axis=1 ) # 每列/行求均值
df.max(axis=1 ) # 每列/行求最大值
df.min(axis=1) # 每列/行求最小值
df.median(axis=1) # 每列/行求中间值
df.mode(axis=1) # 每列/行中出现最多的值
df.var(axis=1) # 每列/行求方差
df.std(axis=1) # 每列/行求标准差
df.quantile(0.25) # 求1/4分位数，可以0.5、0.75等分位数
df.corr() # 求整个DataFrame表中的相关性
~~~

不得不说，df.corr() 实在太好用了

## 数据预处理

我们拿到的数据集，很少是可以直接使用的。pandas为我们提供了比较丰富的预处理函数。比如，面对丢失的值时：

~~~python
# 判断哪个值是缺失值，如果缺失返回True，否则为False
df.isnull()              

df.dropna() # 默认删除含缺失值的行
df.dropna(how=’all’) # 删除全为空值的行，不全为空值的行不会删除2
df.fillna(0) # 用0填充所有空值
df.fillna({‘Sex’:’male’,’Age’:’30’}) # 对性别列中空值填充男，年龄填充30

~~~

另一个常用操作是去重，即舍弃重复值：

~~~python

df.fillna({‘Sex’:’male’,’Age’:’30’}) # 对性别列中空值填充男，年龄填充30
df.drop_duplicates() # 默认对所有值进行重复值检查，保留第一行的值
df.drop_duplicates(subset=’Sex’)  # 对性别列中重复值查询保留第一行
df.drop_duplicates(subset=[’Sex’,’Age’]，keep=’last’)  # 对性别和公司两列查重keep设置默认为first（保留第一个），可设置为last（保留最后一个） 或False(不部不保留)

~~~

我们还经常性的改一下df中的数据格式。比较常见的是一个数值会被误认为是一个字符串，之类的情况吧：


~~~python

df[‘Age’].dtype  # 查看ID列的数据类型
df[‘Age’].astype(‘float’)  # 将ID列的数据类型转换为float类型

~~~

最后，操作index也是必备的。

pandas基础语法中一个重要的概念是index。索引的概念有点像SQL的主键，不过它的功能更强大，分析师能够很轻松的通过索引选取一个数据或者一组数据。一般情况下，我们尽可能的不去动索引，容易乱；但是你要是非要动也可以，比如：


~~~python

# 索引排序
df.sort_index()

df.columns=[‘a’,’b’,’c’]   # 为无索引表添加列索引
df.index=[1,2,3]   # 添加行索引
df.set_index(‘PassengerId’)  # 指明要用的列作为行索列
df.rename(index={‘PassengerId’:’NewPassengerId’}) 对行索引进行重新命名
df.rename(columns={1:’一’,2:’二’}) # 对列索引进行重新命名
df.reset_index() # 默认将全部index转化为column
df.reset_index(level=0) # 将0级索引转化为column
df.reset_index(drop=True) # 删除原有索引

~~~


在此我们不讨论双重索引了，虽然很好用，先简单点的常规操作来一遍。双重或者多重索引可以作为思考题留给大家琢磨。

In [36]:
data

Date        AAPL         AMZN          FB         GOOG        NFLX
0     2009-12-31   26.061205   134.520004         NaN   308.832428    7.870000
1     2010-01-04   26.466835   133.899994         NaN   312.204773    7.640000
2     2010-01-05   26.512596   134.690002         NaN   310.829926    7.358572
3     2010-01-06   26.090879   132.250000         NaN   302.994293    7.617143
4     2010-01-07   26.042646   130.000000         NaN   295.940735    7.485714
...          ...         ...          ...         ...          ...         ...
2594  2020-04-23  274.287506  2399.449951  185.130005  1276.310059  426.700012
2595  2020-04-24  282.206085  2410.219971  190.070007  1279.310059  424.989990
2596  2020-04-27  282.405548  2376.000000  187.500000  1275.880005  421.380005
2597  2020-04-28  277.827911  2314.080078  182.910004  1233.670044  403.829987
2598  2020-04-29  286.953247  2372.709961  194.190002  1341.479980  411.890015

[2599 rows x 6 columns]

# 6. Get Data

In [40]:
import pandas_datareader.data as web

In [ ]:
symbol = 'WIKI/AAPL'  # or 'AAPL.US'
df = web.DataReader(symbol, 'quandl', '2015-01-01', '2017-03-05',api_key='FiaPBJnUr_NDoMM4BW7o')
#   FiaPBJnUr_NDoMM4BW7o

## 6.1 FRED

In [ ]:
from fredapi import Fred as Fred

fred_key='ffc8bae82c04b73a42221721a114855a'
fred = Fred(api_key=fred_key)

In [ ]:
employee_us = fred.get_series('PAYEMS','2022-01-01')
tbill3m = fred.get_series('DTB3','2022-01-01')
fx_usdcny = fred.get_series('DEXCHUS','2022-01-01')
ffr = fred.get_series('DFF','2022-01-01')
uscpi = fred.get_series('CORESTICKM159SFRBATL','2022-01-01')
export_china = fred.get_series('XTEXVA01CNM664S','2022-01-01')

## 6.2 pandas_datareader (Yahoo!)

In [ ]:
import pandas_datareader as datareader

In [ ]:
sh = datareader.data.DataReader('000001.SS', 'yahoo')
sh

## 6.3 Tushare

In [4]:
import tushare as ts
tushare_token = 'b6c86b5366c2bf38446c46c821e38c26f6db3ee187b8ee8fef470f33'

ts.set_token(tushare_token)
pro = ts.pro_api()

In [9]:
df = pro.query('daily', ts_code='000001.SZ', start_date='20180701', end_date='20180718')
df

ts_code trade_date  open  high   low  close  pre_close  change  pct_chg  \
0   000001.SZ   20180718  8.75  8.85  8.69   8.70       8.72   -0.02    -0.23   
1   000001.SZ   20180717  8.74  8.75  8.66   8.72       8.73   -0.01    -0.11   
2   000001.SZ   20180716  8.85  8.90  8.69   8.73       8.88   -0.15    -1.69   
3   000001.SZ   20180713  8.92  8.94  8.82   8.88       8.88    0.00     0.00   
4   000001.SZ   20180712  8.60  8.97  8.58   8.88       8.64    0.24     2.78   
5   000001.SZ   20180711  8.76  8.83  8.68   8.78       8.98   -0.20    -2.23   
6   000001.SZ   20180710  9.02  9.02  8.89   8.98       9.03   -0.05    -0.55   
7   000001.SZ   20180709  8.69  9.03  8.68   9.03       8.66    0.37     4.27   
8   000001.SZ   20180706  8.61  8.78  8.45   8.66       8.60    0.06     0.70   
9   000001.SZ   20180705  8.62  8.73  8.55   8.60       8.61   -0.01    -0.12   
10  000001.SZ   20180704  8.63  8.75  8.61   8.61       8.67   -0.06    -0.69   
11  000001.SZ   20180703  8.69  8.70  8.45   8.67       8.61    0.06     0.70   
12  000001.SZ   20180702  9.05  9.05  8.55   8.61       9.09   -0.48    -5.28   

           vol       amount  
0    525152.77   460697.377  
1    375356.33   326396.994  
2    689845.58   603427.713  
3    603378.21   535401.175  
4   1140492.31  1008658.828  
5    851296.70   744765.824  
6    896862.02   803038.965  
7   1409954.60  1255007.609  
8    988282.69   852071.526  
9    835768.77   722169.579  
10   711153.37   617278.559  
11  1274838.57  1096657.033  
12  1315520.13  1158545.868

# 7. 转换时间格式（待测试

In [ ]:
# 时间格式：
BS_df[['ConvTermStartDate']] =pd.to_datetime(BS_df[['ConvTermStartDate']].stack()).unstack()
BS_df[['ConvTermEndDate']] =pd.to_datetime(BS_df[['ConvTermEndDate']].stack()).unstack()
BS_df[['Date']] =pd.to_datetime(BS_df[['Date']].stack()).unstack()

# 8. Statistic Table Output

### 8.1 Method 1 (Regressions)

In [1]:
import pandas as pd        
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

df = pd.read_stata('http://www.stata-press.com/data/r14/auto.dta')
df['cons'] = 1

Y = df['mpg']
X1 = df[['weight', 'cons']]
X2 = df[['weight', 'price', 'cons']]
X3 = df[['weight', 'price', 'length', 'cons']]
X4 = df[['weight', 'price', 'length', 'displacement', 'cons']]

reg1 = sm.OLS(Y, X1).fit()
reg2 = sm.OLS(Y, X2).fit()
reg3 = sm.OLS(Y, X3).fit()
reg4 = sm.OLS(Y, X4).fit()

results = summary_col([reg1, reg2, reg3, reg4],stars=True,float_format='%0.2f',
                  model_names=['Model\n(1)', 'Model\n(2)', 'Model\n(3)',  'Model\n(4)'],
                  info_dict={'N':lambda x: "{0:d}".format(int(x.nobs)),
                             'R2':lambda x: "{:.2f}".format(x.rsquared)})

In [3]:
results

<class 'statsmodels.iolib.summary2.Summary'>
"""

==================================================
                Model    Model    Model    Model  
                 (1)      (2)      (3)      (4)   
--------------------------------------------------
R-squared      0.65     0.65     0.67     0.67    
R-squared Adj. 0.65     0.64     0.65     0.65    
cons           39.44*** 39.44*** 49.68*** 50.02***
               (1.61)   (1.62)   (6.33)   (6.41)  
displacement                              0.00    
                                          (0.01)  
length                           -0.10*   -0.09   
                                 (0.06)   (0.06)  
price                   -0.00    -0.00    -0.00   
                        (0.00)   (0.00)   (0.00)  
weight         -0.01*** -0.01*** -0.00*   -0.00*  
               (0.00)   (0.00)   (0.00)   (0.00)  
N              74       74       74       74      
R2             0.65     0.65     0.67     0.67    
==================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01
"""

In [ ]:
results_text = results.as_text()

import csv
resultFile = open("table.csv",'w')
resultFile.write(results_text)
resultFile.close()

### 8.2 Single Table

In [4]:
# Linear Regression
import numpy as np
import pandas as pd
from sklearn import datasets # get the dataset
#from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

In [5]:
# Import a Dataset
dataset = datasets.load_diabetes()

# Concate that Dataset, as confirm X & Y
X = pd.DataFrame(dataset.data)
Y = pd.DataFrame(dataset.target)
YX = pd.concat([Y,X],axis=1)

# Through this Method, we need mannually add a contant vector.
x = sm.add_constant(X)

In [6]:
# Regress and Get Results
results = sm.OLS(Y,x).fit()
Y_predict = results.predict(x)
results.summary() 

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      0   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Thu, 17 Nov 2022   Prob (F-statistic):           3.83e-62
Time:                        10:58:13   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.1335      2.576     59.061      0.000     147.071     157.196
0            -10.0122     59.749     -0.168      0.867    -127.448     107.424
1           -239.8191     61.222     -3.917      0.000    -360.151    -119.488
2            519.8398     66.534      7.813      0.000     389.069     650.610
3            324.3904     65.422      4.958      0.000     195.805     452.976
4           -792.1842    416.684     -1.901      0.058   -1611.169      26.801
5            476.7458    339.035      1.406      0.160    -189.621    1143.113
6            101.0446    212.533      0.475      0.635    -316.685     518.774
7            177.0642    161.476      1.097      0.273    -140.313     494.442
8            751.2793    171.902      4.370      0.000     413.409    1089.150
9             67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# 9. String in DataFrame

In [ ]:
df.index.str.split('.').str[-1]

In [ ]:
df.index.str.replace(' ','')

# 10. Create Date Features

In [ ]:
from pandas.api.types import CategoricalDtype
cat_type = CategoricalDtype(categories=['Monday','Tuesday',
                                        'Wednesday',
                                        'Thursday','Friday',
                                        'Saturday','Sunday'],
                            ordered=True)


def create_features(df, label = None):
    df = df.copy()
    df['date'] = df.index
    df['hour'] = df['date'].dt.hour
    df['dayofweek'] = df['date'].dt.dayofweek
    df['weekday'] = df['date'].dt.day_name()
    df['weekday'] = df['weekday'].astype(cat_type)
    df['quarter'] = df['date'].dt.quarter
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year
    df['dayofyear'] = df['date'].dt.dayofyear
    df['dayofmonth'] = df['date'].dt.day
    df['weekofyear'] = df['date'].dt.weekofyear
    df['date_offset'] = (df.date.dt.month*100 + df.date.dt.day - 320)%1300
    df['season'] = pd.cut( df['date_offset'], [0,300,602,900,1300] ,
                          labels = ['Spring', 'Summer', 'Fall', 'Winter'])
    X = df[['hour','dayofweek','quarter','month','year',
            'dayofyear','dayofmonth','weekofyear','weekday',
            'season']]
    if label:
        y = df[label]
        return X,y
    return X

# 11. Subplots

In [ ]:
fig, axs = plt.subplots( 5, 1, figsize=(15,15), sharex=True )

fold = 0
for train_idx, val_idx in tss.split(df):
    train = df.iloc[train_idx]
    test = df.iloc[val_idx]
    
    train['PJME_MW'].plot(ax=axs[fold], 
                          label='Training Set', 
                          title=f'Data Train/Test Split Fold {fold}')
    test['PJME_MW'].plot(ax=axs[fold], 
                         label='Test Set')
    axs[fold].axvline( test.index.min(), color='black', ls='--' )
    fold += 1

# 12. Get dummy

In [ ]:
pd.get_dummy( df )

# 13. Select and Shuffle

In [73]:
array = np.arange(32)

In [74]:
# Select one from the array
np.random.choice(array)

11

In [82]:
# 将32支球队随机分三组
a = np.random.choice(array, size = 11, replace = False)
array = np.setdiff1d(array, a)
b = np.random.choice(array, size = 11, replace = False)
c = np.setdiff1d(array, b)


print(a)
print(b)
print(c)

[20 28  1  0  9  7 25 29  2 31 27]
[26  3 14 30 19 22  4 16  8 18  6]
[ 5 10 11 12 13 15 17 21 23 24]


In [83]:
# 比对两个array，返回 differ的值
np.setdiff1d(array, a)

array([ 3,  4,  5,  6,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22,
       23, 24, 26, 30])

In [37]:
# shuffle an array
np.random.shuffle(array)

https://blog.finxter.com/how-to-remove-specific-elements-in-a-numpy-array/

## 13. Remove an Arrary from Another

### Method 1.   `np.delete`   delete only index not value

In [98]:
array = np.arange(32)
np.random.shuffle(array)

In [100]:
array = np.arange(32)
np.random.shuffle(array)
a = np.random.choice(array, size = 11, replace = False)
deleted_indice = [1,3]

In [101]:
# elements in the index [1, 3] are deleted
np.delete(array, deleted_indice)

array([31, 12,  5, 23, 28, 26,  3, 17,  7,  6, 20, 25,  8, 22,  4, 14, 19,
       21, 24,  9, 30, 10, 11, 16,  1, 15, 27, 18,  2, 29])

### Method 2. `np.where` can filter elements/values

`np.where(  ,   ,  )`

The 1st element is the filter condition, if

The 2nd element is the return if ture

The 3rd element is the return if False

In [107]:
array

array([31, 13, 12,  0,  5, 23, 28, 26,  3, 17,  7,  6, 20, 25,  8, 22,  4,
       14, 19, 21, 24,  9, 30, 10, 11, 16,  1, 15, 27, 18,  2, 29])

In [113]:
np.where(array<16, array, 0 )

array([ 0, 13, 12,  0,  5,  0,  0,  0,  3,  0,  7,  6,  0,  0,  8,  0,  4,
       14,  0,  0,  0,  9,  0, 10, 11,  0,  1, 15,  0,  0,  2,  0])

In [120]:
np.where((array == 1) | (array ==2) , array, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 2, 0])

###### `np.where` 不传入return值可以返回valude对应的 index，此后在传入 `np.delete` 即可

In [123]:
array

array([31, 13, 12,  0,  5, 23, 28, 26,  3, 17,  7,  6, 20, 25,  8, 22,  4,
       14, 19, 21, 24,  9, 30, 10, 11, 16,  1, 15, 27, 18,  2, 29])

In [125]:
# 直接delete会删除 index对应的值，而不是value对应的值
np.delete(array, [1,2])

array([31,  0,  5, 23, 28, 26,  3, 17,  7,  6, 20, 25,  8, 22,  4, 14, 19,
       21, 24,  9, 30, 10, 11, 16,  1, 15, 27, 18,  2, 29])

In [127]:
# 通过`np.where`找到value对应的index后，传入`np.delete`即可删除
deleted_index = np.where((array == 1) | (array ==2))
np.delete(array, deleted_index)

array([31, 13, 12,  0,  5, 23, 28, 26,  3, 17,  7,  6, 20, 25,  8, 22,  4,
       14, 19, 21, 24,  9, 30, 10, 11, 16, 15, 27, 18, 29])

### Method 3. `np.setdiff1d`

In [93]:
np.setdiff1d(array, a)

array([ 0,  1,  4,  5,  6,  7, 10, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22,
       25, 26, 30, 31])

### Method 4. `np.isin`

In [139]:
# np.isin 可以返回bool list
np.isin(array, a)

array([ True, False,  True, False, False, False,  True,  True, False,
        True, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True,  True, False, False,
        True, False, False, False,  True])

In [134]:
# return elements same in array a
array[np.isin(array, a)]

array([31, 12, 28, 26, 17, 19, 21, 10, 11, 15, 29])

In [141]:
# return elements excepted in array a
array[~ np.isin(array, a)]

array([13,  0,  5, 23,  3,  7,  6, 20, 25,  8, 22,  4, 14, 24,  9, 30, 16,
        1, 27, 18,  2])

### Method 5. `np.in1d`

In [143]:
array[np.in1d(array, a)]

array([31, 12, 28, 26, 17, 19, 21, 10, 11, 15, 29])

### Method 6. Compare in a list [ ]

In [159]:
for i, val in enumerate(array):
    if i in deleted_indice:
        print(i,val)

1 13
3 0


In [160]:
[val for i,val in enumerate(array) if i in deleted_indice]

[13, 0]

In [161]:
{i:val for i,val in enumerate(array) if i in deleted_indice}

{1: 13, 3: 0}

# 14. flip a dictionary

In [ ]:
def dict_flip(dict_source):
    dict_flipped = {}
    for key, value in dict_source.items():
        if value not in dict_flipped:
            dict_flipped[value] = [key]
        else:
            dict_flipped[value].append(key)
    return dict_flipped