In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use('fivethirtyeight')

# 1. Example - maximisation with constrain - in Slide, Page 48-67

Assume there 4 assets in the market, $X_1, X_2, X_3, X_4$. With $\mu$ and $\sigma$ and correlation, $R$, showing below,

In [5]:
mu = np.array([0.05, 0.07, 0.15, 0.27])
sigma = np.array([0.07, 0.12, 0.3 , 0.6])
R = np.array([[1,0.8, 0.5, 0.4],[0.8, 1, 0.7, 0.5], [0.5, 0.7, 1, 0.8],[0.4, 0.5, 0.8, 1]])
m = 0.1

The variance-covariance matrix is,

$$\Sigma = SRS$$

, where $S$ matrix is put the vector $\sigma$ into the diagonal elements.

In [31]:
S = np.diag(sigma)
Sigma = np.dot(np.dot(S,R),S)
print(Sigma)

A = np.dot(np.dot(One.T , np.linalg.inv(Sigma)),One)
B = np.dot(np.dot(mu.T, np.linalg.inv(Sigma)), One)
C = np.dot(np.dot(mu.T, np.linalg.inv(Sigma)), mu)

lam = (A*m - B)/(A*C - B**2)
gam = (C - B*m)/(A*C - B**2)

[[0.0049  0.00672 0.0105  0.0168 ]
 [0.00672 0.0144  0.0252  0.036  ]
 [0.0105  0.0252  0.09    0.144  ]
 [0.0168  0.036   0.144   0.36   ]]


In [37]:
w_star = np.dot(np.linalg.inv(Sigma),(lam * mu + gam * One))
w_star

array([0.52841211, 0.17288808, 0.15976434, 0.13893547])

# Another Example, Page 76-89

$$min_{w} \frac{1}{2}w^T \Sigma w$$

$$s.t.\quad  r_f + w^T (\mu - r_f \mathbb{1}) = m$$

Apply the Lagrangian Method,

$$L(x,\lambda) = \frac{1}{2}w^t\Sigma w + \lambda \bigg(m - r_f + w^T (\mu - r_f \mathbb{1})\bigg)$$

F.O.C.  w.r.t. w
$\frac{\partial L}{\partial w} = \Sigma w - \lambda(\mu - r_f \mathbb{1})$

$$w^* = \lambda \Sigma^{-1} (\mu - r_f \mathbb{1})$$


F.O.C. w.r.t. $\lambda$
$$r_f + w^T (\mu - r_f \mathbb{1}) = m$$
, substitute $w^*$ into the above function we could solve for $\lambda^*$

$$\lambda^* = \frac{m-r}{\big( \mu - r_f \mathbb{1} \big)^T \Sigma^{-1}\big( \mu - r_f \mathbb{1} \big) }$$

So,

$$w^* = \frac{(m-r)\Sigma^{-1}(\mu - r_f \mathbb{1})}{\big( \mu - r_f \mathbb{1} \big)^T \Sigma^{-1}\big( \mu - r_f \mathbb{1} \big) }$$

In [45]:
rf = 0.025

w = (m - rf) * np.dot(np.linalg.inv(Sigma), (mu - rf * One)) / \
    (  np.dot(np.dot((mu - rf * One).T,np.linalg.inv(Sigma)), mu - rf * One)  )
w

array([0.88735248, 0.08126325, 0.15484343, 0.12164862])

# Tangency Portfolio

# Black-Litterman

## Part 1. Prior

In [57]:
Sigma = np.array( [[0.0049, 0.00672, 0.0105, 0.0168], \
                   [0.00672, 0.0144, 0.0252, 0.036],\
                   [0.0105, 0.0252, 0.09, 0.144],
                   [0.0168, 0.036, 0.144, 0.36] ] )
wm = np.array([0.05, 0.4, 0.45, 0.1])
Sm = 0.5

In [60]:
sigma = np.sqrt( wm.T.dot(Sigma).dot(wm) )
lam = 1/sigma*Sm
print('lambda:', lam)

Pi = lam * Sigma.dot(wm)
print('Pi:', Pi)

lambda: 2.236905855664812
Pi: [0.02088823 0.04705555 0.14652852 0.25957056]


In [62]:
T = 10*12 # 10 years 12 months
tau = 1/T

tSigma = tau * Sigma
print(tSigma)

[[4.08333333e-05 5.60000000e-05 8.75000000e-05 1.40000000e-04]
 [5.60000000e-05 1.20000000e-04 2.10000000e-04 3.00000000e-04]
 [8.75000000e-05 2.10000000e-04 7.50000000e-04 1.20000000e-03]
 [1.40000000e-04 3.00000000e-04 1.20000000e-03 3.00000000e-03]]


## Part 2. Part 2 - Conditional Dist

In [66]:
P = np.array(  [[-1,0, 1, 0],[0, 1, 0, 0]]  )
Q = np.array([0.1, 0.03])

In [85]:
Omega = tau * P.dot(Sigma).dot(P.T)
print(Omega)
print('-'*20)
Omega1 = np.diag(np.diag(Omega))
print(Omega1)

[[0.00061583 0.000154  ]
 [0.000154   0.00012   ]]
--------------------
[[0.00061583 0.        ]
 [0.         0.00012   ]]


## Posterior

In [ ]:
Rhat = 

In [94]:
denominator = np.linalg.inv(np.linalg.inv(tau*Sigma) + P.T.dot(np.linalg.inv(Omega)).dot(P))
numerator = np.linalg.inv(tau*Sigma).dot(Pi) + P.T.dot(np.linalg.inv(Omega)).dot(Q)
np.dot(denominator, numerator)

array([0.01702165, 0.03852778, 0.1298418 , 0.23522287])

array([-133.6373884 ,  168.64599088,  267.85173974,   26.84287027])